### ISSUE TITLE
Getting the Demo page to work with Vue2

### ISSUE THREAD

**Issue by mesqueeb** [simplesmiler/vue-focus#10]
Dear @simplesmiler . Your example was created with Vue 1, and I'm trying to recreate it with Vue2 here:
See the Pen <a href="http://codepen.io/mesqueeb/pen/qRwLRV/">Vue Focus</a> by Luca Ban

But it doesn't work fully...

I'm still not a pro at vue, so I have some difficulties getting vue-focus to work. I'd like to see how it works with a working example with Vue2. : )

**Comment by simplesmiler** [comment]
Hi @mesqueeb, sorry for taking some time to respond.

I was sure I updated the demo for v2, but apparently I did only update the [internal example](https://github.com/simplesmiler/vue-focus/blob/2.1.0/examples/index.html).

Here is the v2 demo: https://jsfiddle.net/simplesmiler/zak1t6o8/
I will also update the link in the README.md.
