### ISSUE TITLE
bundle size

### ISSUE THREAD

**Issue by codeofsumit** [simplesmiler/vue-focus#15]
is the calculation wrong here?
this seems way too big for a directive
![image](https://user-images.githubusercontent.com/2399810/30445622-dcb7ae4a-9986-11e7-9e18-8a438f1b3b2a.png)

**Comment by jessegavin** [comment]
I am wondering if, because the first line of code does `import Vue from 'vue'`, the editor plugin you're using includes the entire Vue package in that calculation.

The minified build result of `vue-focus` is 445 bytes.

**Comment by codeofsumit** [comment]
hmmm might be.

**Comment by simplesmiler** [comment]
As @jessegavin suggested, this is exactly the reason.

In the future, I will rewrite the code slightly to get the reference to `Vue` from the code consumer instead.
