### ISSUE TITLE
Make Vue plugin

### ISSUE THREAD

**Issue by simshaun** [simplesmiler/vue-focus#4]
It'd be nice if all the directives could be made available globally by calling `Vue.use(VueFocus)`.

https://vuejs.org/guide/plugins.html

**Comment by simplesmiler** [comment]
Sorry for taking so long to response.
I don't really like the plugin style, because it promotes implicit dependencies and may cause conflicts.
If you really want to make things global, you can use `Vue.mixin`:

``` js
var VueFocus = require('vue-focus');
Vue.mixin(VueFocus.mixin);
```
