### ISSUE TITLE
CDN not working

### ISSUE THREAD

**Issue by nueverest** [simplesmiler/vue-focus#5]
The CDN link `<script src="https://cdn.rawgit.com/simplesmiler/vue-focus/0.1.2/dist/vue-focus.js"></script>` is not working.

**Comment by nueverest** [comment]
I submitted a request to cdnjs.com [https://github.com/cdnjs/cdnjs/issues/8859](https://github.com/cdnjs/cdnjs/issues/8859)

**Comment by PeterDaveHello** [comment]
cdnjs/cdnjs#8859 merged, will be available within 20 mins.

**Comment by simplesmiler** [comment]
Sorry for taking so long to respond.
The rawgit link seems to be working for me, but cdnjs is better. Thanks for submitting a PR to them.
I've updated the CDN link in the readme.
