### ISSUE TITLE
Vue 2.0 - Uncaught TypeError: Cannot read property 'focus' of undefined.

### ISSUE THREAD

**Issue by nueverest** [simplesmiler/vue-focus#6]
I realize that I'm pushing the limits here by trying to use this code snippet in Vue 2.0.

That said, line 13 `self.el.focus();` produces an error under Vue 2.0.  

`Uncaught TypeError: Cannot read property 'focus' of undefined.` and the `nextTickHandler` is identified in the vue 2.0 JS file.

```
var focusAuto = {
    priority: 100,
    bind: function() {
        var self = this;
        this.bound = true;

        var Vue__default = 'default' in Vue ? Vue['default'] : Vue;
        Vue__default.nextTick(function() {
            if (self.bound === true) {
                self.el.focus();
            }
        });
    },
    unbind: function(){
        this.bound = false;
    }
};
```

**Comment by simplesmiler** [comment]
Hi! Sorry for taking so long to respond.
I've opened an [2.0 support issue](https://github.com/simplesmiler/vue-focus/issues/7).
